apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: dockerhub-sa  # Use the created service account
      containers:
      - name: my-container
        image: maheshmojo/hello_python:2  # Replace with your image
        ports:
        - containerPort: 5000
